import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useSession } from "next-auth/client";

export default function Home() {
  const [session, loading] = useSession();
  console.log({ session, loading });
  return (
  
    <div className={styles.container}>
      <Head>
        <title>Know Me Better</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet"> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <b className={styles.project}>Know Me Better </b>
        </h1>
        <h1 className={styles.subtitle}>
          A Portfolio Generator Website for Devs!
        </h1>
        <br />

        <br />

        <br />
        <h1 className={styles.subtitlename}>
          {/* Making use of Next Auth Provider */}{" "}
          {session ? `Welcome ${session.user.name}!` : ""}
        </h1>
      </main>
      
    </div>

    
  );
}
